#pragma once
#include "player/Player.h"
#include "menuActions/adventureAction.h"
#include "menuActions/trainingAction.h"
#include "menuActions/restAction.h"
#include "menuActions/viewCharacterAction.h"
#include "menuActions/viewInventoryAction.h"
#include "menuActions/viewJournalAction.h"
#include "menuActions/viewEquipmentAction.h"